### ISSUE TITLE
DeepLabCut Issue Where Deleting Frames During Labeling Causes Training Dataset to Not Form; Program Looks for Deleted Data

### ISSUE THREAD

**Issue by samueljrosen** [DeepLabCut/DeepLabCut#1134]
Thanks for opening this issue, and thanks for using DeepLabCut (we hope you are enjoying it ;). Please fill out the template completely, including the full "traceback" and input code that you ran to hit this error.

**Your Operating system and DeepLabCut version**

Please state your operating system, env, and which version of DeepLabCut you are using.
Example: Windows 10 with an Anaconda Env, & DeepLabCut 2.2
Please complete the following information about your system:

OS: Windows 10
DeepLabCut Version: 2.2
Anaconda env used: DLC-GPU

**Describe the problem**

I deleted frames when labeling my data. Now when I go to make a training set with this data I get repeated errors that DeepLabCut cannot find the files I deleted. I checked the CSVs made when labeling is completed and I see blanks where the deleted files should be, so I don't know what triggers this error. I use the GUI version for reference as well.

Please place code inside this:

<details><summary>C:\Users\rosen\Desktop\Rosen_DeepLabCut\Melano_DLC_Rosen-Melano_DLC_Rosen-2021-03-03\training-datasets\iteration-0\UnaugmentedDataSet_Melano_DLC_RosenMar3  already exists!
Traceback (most recent call last):
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 385, in create_training_dataset
    augmenter_type=self.aug_choice.GetValue(),
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 1020, in create_training_dataset
    Data, trainIndices, nbodyparts, project_path
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 793, in format_training_data
    img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 777, in _read_image_shape_fast
    return io.imread(path).shape
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\request.py", line 124, in __init__
    self._parse_uri(uri)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'C:\Users\rosen\Desktop\Rosen_DeepLabCut\Melano_DLC_Rosen-Melano_DLC_Rosen-2021-03-03\labeled-data\022221_Melano_Video001_SOFT\img8101.png'</summary><p>

[Please copy/paste the full terminal output of the error here!!!]

</p></details>

**How to Reproduce the problem**
1. Open DeepLabCut and go to 'Label Frames'
2. Label data and use the delete frames button to remove bad frames from your data set
3. Finish labeling, hit save and exit out of the labeling menu
4. Click 'Create training dataset' and click OK, and see the error magically appear right on your very own screen

**Comment by KonradDanielewski** [comment]
There was a bug in 2.2 version with delete button. Issue should be resolved when you update deeplabcut to newest version

**Comment by samueljrosen** [comment]
I upgraded my DeepLabCut to 2.2b8 and still get the same error

**Comment by backyardbiomech** [comment]
@samueljrosen, 2.1.10.2 is the newest version. 2.2b is no longer being developed, but all features have been rolled into 2.1.10+

**Comment by samueljrosen** [comment]
Ok! I just updated my DeepLabCut to the version you listed and I still get the following error:

C:\Users\rosen\Desktop\Rosen_DeepLabCut\Melano_DLC_Rosen-Melano_DLC_Rosen-2021-03-03\training-datasets\iteration-0\UnaugmentedDataSet_Melano_DLC_RosenMar3  already exists!
Traceback (most recent call last):
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\gui\create_training_dataset.py", line 385, in create_training_dataset
    augmenter_type=self.aug_choice.GetValue(),
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 1020, in create_training_dataset
    Data, trainIndices, nbodyparts, project_path
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 793, in format_training_data
    img_shape = _read_image_shape_fast(os.path.join(project_path, filename))
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\deeplabcut\generate_training_dataset\trainingsetmanipulation.py", line 777, in _read_image_shape_fast
    return io.imread(path).shape
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\manage_plugins.py", line 209, in call_plugin
    return func(*args, **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\skimage\io\_plugins\imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 265, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\functions.py", line 172, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\request.py", line 124, in __init__
    self._parse_uri(uri)
  File "C:\Users\rosen\Anaconda3\envs\DLC-GPU\lib\site-packages\imageio\core\request.py", line 260, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'C:\Users\rosen\Desktop\Rosen_DeepLabCut\Melano_DLC_Rosen-Melano_DLC_Rosen-2021-03-03\labeled-data\022221_Melano_Video001_SOFT\img8101.png'

If there's any additional information you would like me to post, please let me know since I don't know why it keeps throwing errors for deleted frames. I did delete the frames in the old version, would I have to do relabeling in this version of DeepLabCut?

**Comment by KonradDanielewski** [comment]
Maybe there are annotation entries left in CollectedData. Please use `deeplabcut.dropannotationfileentriesduetodeletedimages(config)` and see what happens. Try and check_labels after to see if everything is okay with your labelling.

**Comment by AlexEMG** [comment]
Yes, that's a thorny one. You need to carefully compare images & annotations, with the helper functions mentioned by @KonradDanielewski (also more in the user guide) and then it should be fine!

**Comment by GPU-Shuttle** [comment]
Here's the somehow similar error I am facing atm!
I had a project setup and working on the server; I was wanting to add a new participant to the dataset; hence labelled data from that new participant.
Then I created a new project on the server by including video from the new participant in the initial set-up. Then copied the previous "labeled-data" folder to the new project and also uploaded/added the labeled data (including the .csv and .h5 files) from my pc to the "labeled-data";
I face the 
".......raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file:" 
error once I want to create the training dataset! 
The "deeplabcut.dropannotationfileentriesduetodeletedimages(config)" command drops all the images related to the subject that I have labeled on my pc (and removes the markers coordinates from the .csv file :-( )! not sure what I should do to solve this. I would appreciate if you could comment on that, please?

**Comment by KonradDanielewski** [comment]
You mean you wanted to add new videos to the dataset? If so, then you should just add the video to the project, label frames and create new trainig dataset after which you change init_weights in pose_cfg.yaml and add path to your snapshot from model trained on previous subjects. I don't quite follow why you created a whole new project. 

The first error is probably caused by the path missmatch in config.yaml on your computer vs after uploading to server.

The `deeplabcut.dropannotationfileentriesduetodeletedimages(config)` will remove annotation data if no PNGs are present in the labeled_data folder of corresponding video.

**Comment by GPU-Shuttle** [comment]
Correct, I was wanting to add new videos ... but it's so hard to do it while working on the server due to display lag etc! so I decided to do the labeling on the desktop pc, define a new project on the server including the new videos, and then transfer the "labeled-data" folder from the pc to the server.

Anyway, I feel like I know what the problem is, but I don't know how I'd be able to fix it! it's definitely related to path issues.
I noticed that all the paths to the images in the .csv file from the previous dataset in the 'labeled-data' folder on the server have "/" to address the path/images (e.g., labeled-data/P08_ML/img0002.png); ; whereas the .csv file for the new participant shows " \ " instead (e.g., labeled-data\P10_ML\img0018.png). I think all the " \ "s need to be changed to "/"s. Now wonder how'd be possible to edit this in the .h5 file as I am sure DLC reads from that and not from the .csv file?

Thanks again

**Comment by backyardbiomech** [comment]
The reason for the path separator difference is that you must have labeled the new data on a windows computer.

```
deeplabcut.convertannotationdata_fromwindows2unixstyle(config_path, userfeedback=True, win2linux=True)
```

will ask you (`userfeedback=True`) if you want to convert each video in your `config`, and will convert "\" (windows) to "/" (unix) in the labeled data for those videos. 

If you can't use a GUI on the server for labelling due to lag, I strongly suggest copying your full project folder to your local PC and back to your server (or use some kind of network storage that both computers can access). Unless you are very familiar with the deeplabcut workflow and code, editing the folder structure directly can cause big problems that are hard to track down.

**Comment by GPU-Shuttle** [comment]
Thanks very much for the wonderful comment.
the "deeplabcut.convertannotationdata_fromwindows2unixstyle" command did solve everything and I am back to deeplabcutting!
