### ISSUE TITLE
analyze video stops a 6%-- video corrupted 

### ISSUE THREAD

**Issue by millerlabUCSD** [DeepLabCut/DeepLabCut#1141]
Hi, 
I get this error when using the GUI and getting to the "Create Videos" tab. I choose the same video from the videos folder but I'm not sure why it says the unfiltered data file is not found. 

Error:
Starting to process video: C:\Users\vtngo\Desktop\C2549_Trim.mp4
Loading C:\Users\vtngo\Desktop\C2549_Trim.mp4 and data.
No unfiltered data file found in C:\Users\vtngo\Desktop for video C2549_Trim and scorer DLC_resnet_50_C2549TrimMar11shuffle1_100000.

Can someone suggest what I should do? It was fine when I used GUI for Analyze videos and I get the appropriate .csv and .h5 files in the evaluation-results folder.

**Comment by jeylau** [comment]
The h5 file found in evaluation-results is after network evaluation only. To create a labeled video, make sure you run `deeplabcut.analyze_videos` first; this will produce a h5 data file along the video.

**Comment by millerlabUCSD** [comment]
> The h5 file found in evaluation-results is after network evaluation only. To create a labeled video, make sure you run `deeplabcut.analyze_videos` first; this will produce a h5 data file along the video.

Hi, I did analyze the videos first before trying to create video, but I'm not sure what new file(s) were produced since there's nothing else in the "videos" folder besides the original video I am testing.

When I try to create the labeled video after, I choose the original video that is in the videos folder but I'm not sure if I'm supposed to choose something else from the other folders (dlc-models, evaluation-results, etc.)  since there were no other video files created- just labeled images and csv/h5 text files. Am I supposed to run the original video along with the h5 text file? If so, the h5 text files are in evaluation-results, labeled-data, and training-datasets folders.

**Comment by MMathisLab** [comment]
@millerlabUCSD - indeed you should choose the same video as you picked when you ran "analyze videos." on that tab, you also have the option to check the box "filter predictions". Then on the create video tab, you can check use filtered, etc. Can you check the folder with your "original" video? you should see something like this, i.e. an .h5, a .meta alongside your original video:

![Screen Shot 2021-03-14 at 10 06 55 PM](https://user-images.githubusercontent.com/28102185/111084221-9bd07400-8511-11eb-9c74-2a5766b00cb2.png)

**Comment by millerlabUCSD** [comment]
> @millerlabUCSD - indeed you should choose the same video as you picked when you ran "analyze videos." on that tab, you also have the option to check the box "filter predictions". Then on the create video tab, you can check use filtered, etc. Can you check the folder with your "original" video? you should see something like this, i.e. an .h5, a .meta alongside your original video:
> 
> ![Screen Shot 2021-03-14 at 10 06 55 PM](https://user-images.githubusercontent.com/28102185/111084221-9bd07400-8511-11eb-9c74-2a5766b00cb2.png)

Hi, under the videos file, there is nothing else present besides the original video. Does this mean I missed a step somewhere?
I tried to rerun analyze videos with my original vid and clicked yes to filter the predictions but ran into another error: 

2021-03-15 12:43:18.487417: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at conv_ops.cc:446 : Resource exhausted: OOM when allocating tensor with shape[8,256,540,960] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc |

as well as 

No unfiltered data file found in C:\Users\vtngo\Desktop for video C2549_Trim and scorer DLC_resnet_50_C2549TrimMar11shuffle1_100000.

Please let me know if I should try something differently since I seemed to not run into any errors until the Analyze/Create Videos portion of the GUI.

![Screenshot (3)](https://user-images.githubusercontent.com/77994014/111212205-8ea49b00-858c-11eb-90d3-bde170d89a9e.png)

**Comment by MMathisLab** [comment]
Hi @millerlabUCSD so it says filtered file not found as the video is not analyzing. thanks for the screenshot; here you can see it s**tops at 6%**, which suggests your video is corrupted, at some point the meta data is likely missing. Can you convert your video into another format and try again? 

then as you check plot and filter, it tried to do do those things next, but of course there is no video to filter, and no filtered video found to plot ;).

**Comment by MMathisLab** [comment]
^^ btw, you should also upgrade to the latest DLC, as it will tell you there is an issue, but will finish analyzing your video.

**Comment by millerlabUCSD** [comment]
Hi, 

Thank you for being patient with this case and for your quick responses- I really appreciate it!

Let me try to convert it from .mp4 to .avi and see if that helps. 

Additionally, I tried to upgrade to the latest DLC on windows. 
In Anaconda  Prompt I ran:
pip install -U wxPython==4.0.7.post2 

which installed  numpy-1.20.1 successfully. However, I also ran: 
pip install deeplabcut==2.2b8

which is where I was led to an error saying:
"ERROR: Command errored out with exit status 1:" 
" ERROR: Failed building wheel for numpy"
" ERROR: Failed cleaning build dir for numpy"
" Rolling back uninstall of numpy"

What should I do in this case?

**Comment by backyardbiomech** [comment]
The latest version is 2.1.10.2:
To grab the latest master version run

`pip install git+https://github.com/DeepLabCut/DeepLabCut.git`

**Comment by jeylau** [comment]
Fixed by #1105.

**Comment by millerlabUCSD** [comment]
Hi, 

Just an update but I updated DLC to 2.2b8

Additionally, I converted the video from .mp4 to .avi and the problem is still the same (stops at 6% when analyzing). 

Sorry, I'm not sure where to follow along to post #1105 so I am still stuck. This time around, I only labeled a couple of frames and didn't set as many iterations since I just want to see a successful analysis first. 

I noticed that even in the beginning steps, the video was still corrupted. Do you think I should just try a different video or is there a different problem? 
![Screenshot (6)](https://user-images.githubusercontent.com/77994014/112395490-bba72b00-8cbb-11eb-9e69-305e099fcdcf.png)

**Comment by jeylau** [comment]
The latest DLC version is no longer the beta version b8, it is 2.1.10.2 as mentioned above.  Note though that the fix for video analysis will only be available in the next release (unless you clone the repo now) 😊

**Comment by millerlabUCSD** [comment]
Hmm when I git cloned the repo you posted/upgraded, it did state that the requirement is already up to date (2.1.10.2) but when I checked the version, it still outputs 2.2b8

Is there some way to roll back the beta version?

"(base) C:\Users\vtngo>pip install --upgrade deeplabcut
Requirement already up-to-date: deeplabcut in c:\programdata\anaconda3\lib\site-packages (2.1.10.2)
Requirement already satisfied, skipping upgrade: opencv-python-headless~=3.4.9.33 in c:\programdata\anaconda3\lib\site-packages (from deeplabcut) (3.4.9.33)
Requirement already satisfied, skipping upgrade: tensorpack==0.9.8 in c:\programdata\anaconda3\lib\site-packages (from deeplabcut) (0.9.8)"

**Comment by jeylau** [comment]
You've installed deeplabcut in (base) whereas I suspect you'd like to be in your conda environment; make sure to activate it first before installing packages.

**Comment by millerlabUCSD** [comment]
I'm not sure what I did wrong but I went into the conda environment to git clone the repo but now I can't import deeplabcut 

Just double checking but what version of TensorFlow should I have (TensorFlow 1.13.1 like stated on the website)? I think I need to pip uninstall Tensorflow and maybe reinstall CUDA for my GPU



![Screenshot (8)](https://user-images.githubusercontent.com/77994014/112534729-a89e6480-8d68-11eb-86be-312b215747ac.png)

**Comment by millerlabUCSD** [comment]
I was able to download  2.1.10.2 and it seems like I have a new problem (not enough memory available?)
Any suggestions on how to allocate more memory? When I run nvidia-smi, I can't see the GPU memory storage as it is N/A. 


![Screenshot (12)](https://user-images.githubusercontent.com/77994014/113364532-a4de8500-9308-11eb-9272-5fe498e296f6.png)

![Screenshot (10)](https://user-images.githubusercontent.com/77994014/113364132-92178080-9307-11eb-8d40-6b9821813ed9.png)

![Screenshot (13)](https://user-images.githubusercontent.com/77994014/113364834-609fb480-9309-11eb-8189-72ebd65bcac2.png)
