### ISSUE TITLE
cudart64_110.dll not found

### ISSUE THREAD

**Issue by FraCost** [DeepLabCut/DeepLabCut#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

I installed deeplabcut this morning to use it on my GPU, but when I launch the GUI I get the error below. How can I fix it?
<img width="997" alt="Capture" src="https://user-images.githubusercontent.com/79697082/137465685-40ae22d2-c881-49d2-9314-506b1c423702.PNG">

### Operating System

Windows 10

### DeepLabCut version

dlc version

### DeepLabCut mode

single animal

### Device type

gpu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by jeylau** [comment]
I think `conda install cudnn=8` should fix it; it will also download the right version of cudatoolkit!

**Comment by FraCost** [comment]
Thanks for the quick reply. I tried with the command you suggested but still getting the same error.

**Comment by backyardbiomech** [comment]
You may need to update your driver. I can't remember where exactly the incompatibility is, but something between CUDA 11.2+, tensorflow 2.2+ (or 2.5+), cudnn 8+ required me to update my driver to 471+ to get everything to fall into place.

**Comment by MMathisLab** [comment]
also @FraCost note there are a lot of websites specifically for this issue, as it's a common TF/CUDA/GPU/Driver incompatability: please see, for example: https://ourcodeworld.com/articles/read/1433/how-to-fix-tensorflow-warning-could-not-load-dynamic-library-cudart64-110dll-dlerror-cudart64-110dll-not-found

So, I will close as it's not DLC specific, but do come back and let us know if issues. thanks!
