### ISSUE TITLE
DLC 2.3rc1: GUI fails to launch on Ubuntu20.04

### ISSUE THREAD

**Issue by MitchFuchs** [DeepLabCut/DeepLabCut#2009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

`python -m deeplabcut`

fails to launch GUI on newest DLC 2.3rc1

### Operating System

Ubuntu 20.04
Cuda 11.0
cudnn 8.0.5

_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.2.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.10.3                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
build                     0.8.0                    pypi_0    pypi
ca-certificates           2022.07.19           h06a4308_0  
cachetools                5.2.0                    pypi_0    pypi
cachey                    0.2.1                    pypi_0    pypi
certifi                   2022.9.24        py38h06a4308_0  
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
contourpy                 1.0.5                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dask                      2022.9.2                 pypi_0    pypi
dask-image                2022.9.0                 pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
deeplabcut                2.3rc1                   pypi_0    pypi
docstring-parser          0.15                     pypi_0    pypi
docutils                  0.19                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.1                    pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
flatbuffers               22.9.24                  pypi_0    pypi
fonttools                 4.37.4                   pypi_0    pypi
freetype-py               2.3.0                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               2.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.49.1                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.3                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.22.1                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
imagesize                 1.4.1                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
ipykernel                 6.16.0                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter-client            7.3.5                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
keras                     2.10.0                   pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libclang                  14.0.6                   pypi_0    pypi
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
magicgui                  0.5.1                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.1                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
msgpack-numpy             0.4.8                    pypi_0    pypi
napari                    0.4.16                   pypi_0    pypi
napari-console            0.0.6                    pypi_0    pypi
napari-deeplabcut         0.0.6                    pypi_0    pypi
napari-plugin-engine      0.2.0                    pypi_0    pypi
napari-svg                0.1.6                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.8.7                    pypi_0    pypi
npe2                      0.6.1                    pypi_0    pypi
numba                     0.56.2                   pypi_0    pypi
numexpr                   2.8.3                    pypi_0    pypi
numpy                     1.23.3                   pypi_0    pypi
numpydoc                  1.5.0                    pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.3.0                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pep517                    0.13.0                   pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pint                      0.19.2                   pypi_0    pypi
pip                       22.2.2           py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
psygnal                   0.4.2                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopengl                  3.1.6                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pyside2                   5.15.2.1                 pypi_0    pypi
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytomlpp                  1.0.11                   pypi_0    pypi
pytz                      2022.4                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qdarkstyle                3.1                      pypi_0    pypi
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rich                      12.6.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.2                    pypi_0    pypi
setuptools                59.8.0                   pypi_0    pypi
shapely                   1.8.4                    pypi_0    pypi
shiboken2                 5.15.2.1                 pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
slicerator                1.1.0                    pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    5.2.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlite                    3.39.3               h5082296_0  
stack-data                0.5.1                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
superqt                   0.3.8                    pypi_0    pypi
tables                    3.7.0                    pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.10.0                   pypi_0    pypi
tensorflow-estimator      2.10.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.27.0                   pypi_0    pypi
tensorpack                0.11                     pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
tf-slim                   1.1.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.8.12                pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     1.12.1                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.4.0                    pypi_0    pypi
typer                     0.6.1                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
vispy                     0.10.0                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
wrapt                     1.14.1                   pypi_0    pypi
xz                        5.2.6                h5eee18b_0  
zipp                      3.9.0                    pypi_0    pypi
zlib                      1.2.12               h5eee18b_3  

### DeepLabCut version

DLC 2.3rc1

### DeepLabCut mode

multi animal

### Device type

GPU RTX 2080 Ti

### Steps To Reproduce

```
conda create -y --name DLC_gui python=3.8
conda activate DLC_gui
pip install 'deeplabcut[gui]'==2.3rc1
python -m deeplabcut
```

### Relevant log output

```shell
(DLC_gui) mitch@imi134:~$ python -m deeplabcut
2022-10-11 15:21:49.996921: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-11 15:21:50.149601: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-11 15:21:50.694919: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2022-10-11 15:21:50.694979: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64
2022-10-11 15:21:50.694986: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3rc1...
Starting GUI...
QObject::moveToThread: Current thread (0x55a487ffe3d0) is not the object's thread (0x55a48cdc3c20).
Cannot move to target thread (0x55a487ffe3d0)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl.

*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x17b8ef0)[0x7f3e18f19ef0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7f3e50998420]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f3e507d500b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f3e507b4859]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Core.so.5(_Z13qErrnoWarningPKcz+0x0)[0x7f3d899819bc]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate25createPlatformIntegrationEv+0x1530)[0x7f3d8a24cfa0]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate21createEventDispatcherEv+0x2d)[0x7f3d8a24d2ad]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate4initEv+0xd83)[0x7f3d89b93fe3]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate4initEv+0x1c)[0x7f3d8a24fccc]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/Qt/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate4initEv+0x9)[0x7f3d8ab7daa9]
/home/mitch/miniconda3/envs/DLC_gui/lib/python3.8/site-packages/PySide2/QtWidgets.abi3.so(+0x197be4)[0x7f3d8b656be4]
python(_PyObject_MakeTpCall+0x228)[0x55a483762fa8]
python(_PyEval_EvalFrameDefault+0x5434)[0x55a48380ddd4]
python(_PyFunction_Vectorcall+0x1b7)[0x55a4837ff7e7]
python(_PyEval_EvalFrameDefault+0x71b)[0x55a4838090bb]
python(_PyEval_EvalCodeWithName+0x260)[0x55a4837fe600]
python(+0x1f98df)[0x55a48382b8df]
python(+0x13b23d)[0x55a48376d23d]
python(_PyEval_EvalFrameDefault+0x71b)[0x55a4838090bb]
python(_PyEval_EvalCodeWithName+0x260)[0x55a4837fe600]
python(_PyFunction_Vectorcall+0x534)[0x55a4837ffb64]
python(_PyEval_EvalFrameDefault+0x71b)[0x55a4838090bb]
python(_PyEval_EvalCodeWithName+0x260)[0x55a4837fe600]
python(_PyFunction_Vectorcall+0x534)[0x55a4837ffb64]
python(PyObject_Call+0x7d)[0x55a48376920d]
python(+0x253a6a)[0x55a483885a6a]
python(Py_RunMain+0x447)[0x55a483888ac7]
python(Py_BytesMain+0x39)[0x55a483888c29]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f3e507b6083]
python(+0x1f9ad7)[0x55a48382bad7]
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	
	gsignal
	abort
	qErrnoWarning(char const*, ...)
	QGuiApplicationPrivate::createPlatformIntegration()
	QGuiApplicationPrivate::createEventDispatcher()
	QCoreApplicationPrivate::init()
	QGuiApplicationPrivate::init()
	QApplicationPrivate::init()
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	
*** End stack trace ***
Aborted (core dumped)
```

### Anything else?

here a few links, which I tried without being successful

https://forum.qt.io/topic/119109/using-pyqt5-with-opencv-python-cv2-causes-error-could-not-load-qt-platform-plugin-xcb-even-though-it-was-found

https://github.com/NVlabs/instant-ngp/discussions/300

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

**Comment by weiluwl** [comment]
Hi @MitchFuchs ,

I experienced the same issue with the newest 2.3rc1. I tried to launch it on a gpu node on  CentOS 8.4.2105.

**Comment by yangyuke001** [comment]
Hi @MitchFuchs ,

I experienced the same issue with the newest 2.3rc1. I tried to launch it on a gpu node on windows10

**Comment by dprotter** [comment]
I fixed this issue by uninstalling opencv-python with pip and re-installing the headless version with conda. I am running into other issues though, but I briefly was able to use the GUI to label images, which make me think this solution is valid

`pip uninstall opencv-python`
`conda install -c fastai opencv-python-headless`

**Comment by MMathisLab** [comment]
@MitchFuchs can you try the latest release?

**Comment by MitchFuchs** [comment]
The console output is different, however the GUI still fails to launch, which seems to be caused by pytorch. Here is my output:

```
2022-11-08 08:43:25.285391: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA 

To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. 

2022-11-08 08:43:25.415027: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered 

2022-11-08 08:43:25.959980: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64 

2022-11-08 08:43:25.960051: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64 

2022-11-08 08:43:25.960059: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly. 

Loading DLC 2.3rc1... 

Traceback (most recent call last): 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/runpy.py", line 185, in _run_module_as_main 

    mod_name, mod_spec, code = _get_module_details(mod_name, _Error) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/runpy.py", line 144, in _get_module_details 

    return _get_module_details(pkg_main_name, error) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/runpy.py", line 111, in _get_module_details 

    __import__(pkg_name) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/deeplabcut/__init__.py", line 74, in <module> 

    from deeplabcut.pose_tracking_pytorch import transformer_reID 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import 

    return original_import(name, *args, **kwargs) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/__init__.py", line 12, in <module> 

    from .train_dlctransreid import train_tracking_transformer 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import 

    return original_import(name, *args, **kwargs) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/deeplabcut/pose_tracking_pytorch/train_dlctransreid.py", line 12, in <module> 

    import torch 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import 

    return original_import(name, *args, **kwargs) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/torch/__init__.py", line 191, in <module> 

    _load_global_deps() 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/torch/__init__.py", line 153, in _load_global_deps 

    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL) 

  File "/home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/ctypes/__init__.py", line 373, in __init__ 

    self._handle = _dlopen(self._name, mode) 

OSError: /home/mitch/miniconda3/envs/DLC_gui2/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 
```

**Comment by MMathisLab** [comment]
hi @MitchFuchs seems you have some issues here with CUDA; what do you have installed? See: https://github.com/pytorch/pytorch/issues/51080

Also after upgrading CUDA for latest, please run: `pip install --upgrade --force-reinstall 'deeplabcut[gui,tf]'==2.3rc2`

**Comment by MitchFuchs** [comment]
Thanks @MMathisLab! 

I confirm that 

`pip install --upgrade --force-reinstall 'deeplabcut[gui,tf]'==2.3rc2`

followed by 

`pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio===0.7.2 -f https://download.pytorch.org/whl/torch_stable.html`

solves the issue (I use CUDA 11.0).  

The command 

`python -m deeplabcut`

successfully lanches the GUI

Best, 
Mitch.

**Comment by dpeg22** [comment]
Hi @jeylau, I seemingly am having the same issue (After following the suggestion in #2118 to only use the DLC conda environment with deeplabcut[tf,gui], although I changed the name to DEEPLABCUT-test to avoid conflicts).
I run:
```
conda env create -f DEEPLABCUT-test.yaml
conda activate DEEPLABCUT-test
python -m deeplabcut
```
and it crashes here. I've tried the following as suggested previously in this issue, which doesn't change the error:
```
pip uninstall opencv-python
pip install opencv-python-headless
```
I have also tried the suggestions [here](https://forum.qt.io/topic/111553/solved-qt-qpa-plugin-could-not-find-the-qt-platform-plugin-xcb-in/2) to no avail. 

I'm running this on Ubuntu 20.04 with a NVIDIA GeForce GT 710 GPU and CUDA 11.4
While I can continue using DLC <2.3 I was hoping to incorporate the bug fix from #2036.

Thanks in advance for any suggestions!
<details><summary><h4>The log output</h4></summary>

```
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqwebgl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/dgramling/anaconda3/envs/DEEPLABCUT-test/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x17b8ef0)[0x7fee417fbef0]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420)[0x7fee79803420]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7fee794dc00b]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7fee794bb859]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(+0x9441a)[0x7fedb2a6c41a]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(_ZNK14QMessageLogger7warningEPKcz+0x0)[0x7fedb2a6cb4c]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(+0x113f0f)[0x7fed94efff0f]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate25createPlatformIntegrationEv+0x702)[0x7fed94f9f142]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate21createEventDispatcherEv+0x30)[0x7fed94f9fbd0]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(_ZN23QCoreApplicationPrivate4initEv+0xe56)[0x7fedb2b01466]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate4initEv+0x20)[0x7fed94fa1aa0]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Widgets.so.6(_ZN19QApplicationPrivate4initEv+0x9)[0x7fed958ecab9]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17ecf0)[0x7fed96010cf0]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17ed62)[0x7fed96010d62]
/home/dgramling/anaconda3/envs/DEEPLABCUT-test/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17f3e2)[0x7fed960113e2]
python(_PyObject_MakeTpCall+0x51c)[0x564379e9755c]
python(_PyEval_EvalFrameDefault+0x4d64)[0x564379e93374]
python(_PyFunction_Vectorcall+0xf6)[0x564379e9f1d6]
python(_PyEval_EvalFrameDefault+0x38b)[0x564379e8e99b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x564379e8d351]
python(PyEval_EvalCodeEx+0x39)[0x564379f4cfe9]
python(PyEval_EvalCode+0x1b)[0x564379f4cfab]
python(+0x1df30d)[0x564379f5130d]
python(+0x12deb8)[0x564379e9feb8]
python(_PyEval_EvalFrameDefault+0x38b)[0x564379e8e99b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x564379e8d351]
python(_PyFunction_Vectorcall+0x18c)[0x564379e9f26c]
python(_PyEval_EvalFrameDefault+0x38b)[0x564379e8e99b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x564379e8d351]
python(_PyFunction_Vectorcall+0x18c)[0x564379e9f26c]
python(PyObject_Call+0x2d2)[0x564379eb10a2]
python(+0x1f805b)[0x564379f6a05b]
python(Py_RunMain+0xcc)[0x564379f6989c]
python(Py_BytesMain+0x39)[0x564379f41329]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fee794bd083]
python(+0x1cf235)[0x564379f41235]
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
	tensorflow::CurrentStackTrace[abi:cxx11]()
	
	
	gsignal
	abort
	
	QMessageLogger::warning(char const*, ...) const
	
	QGuiApplicationPrivate::createPlatformIntegration()
	QGuiApplicationPrivate::createEventDispatcher()
	QCoreApplicationPrivate::init()
	QGuiApplicationPrivate::init()
	QApplicationPrivate::init()
	
	
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	
	Py_RunMain
	Py_BytesMain
	__libc_start_main
	
*** End stack trace ***
Aborted (core dumped)
```
</details>

**Comment by Mitchellb16** [comment]
I'm running on Ubuntu 20.04.1 LTS with an NVIDIA RTX A5000 and cuda 11.3.0, getting a similar issue to @dpeg22 (also following the above instructions). 

Log output: 
```
python -m deeplabcut
2023-01-19 16:01:08.871617: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-01-19 16:01:09.003074: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-01-19 16:01:09.006524: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-01-19 16:01:09.006544: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-01-19 16:01:09.668806: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-19 16:01:09.668868: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-19 16:01:09.668876: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Loading DLC 2.3rc2...
Starting GUI...
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqeglfs.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqminimal.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqminimalegl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqoffscreen.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqvnc.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqwebgl.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.core.plugin.loader: In /home/mitchell/anaconda3/envs/DEEPLABCUT/plugins/platforms/libqxcb.so:
  Plugin uses incompatible Qt library (5.15.0) [release]
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/cv2/qt/plugins"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

*** Received signal 6 ***
*** BEGIN MANGLED STACK TRACE ***
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/tensorflow/python/../libtensorflow_framework.so.2(+0x16d6220)[0x7ff39df1b220]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7ff3d6753520]
/lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7ff3d67a7a7c]
/lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7ff3d6753476]
/lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7ff3d67397f3]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(+0x9441a)[0x7ff2d2e0f41a]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(_ZNK14QMessageLogger7warningEPKcz+0x0)[0x7ff2d2e0fb4c]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(+0x113f0f)[0x7ff2cf6eef0f]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate25createPlatformIntegrationEv+0x702)[0x7ff2cf78e142]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate21createEventDispatcherEv+0x30)[0x7ff2cf78ebd0]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Core.so.6(_ZN23QCoreApplicationPrivate4initEv+0xe56)[0x7ff2d2ea4466]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Gui.so.6(_ZN22QGuiApplicationPrivate4initEv+0x20)[0x7ff2cf790aa0]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/Qt/lib/libQt6Widgets.so.6(_ZN19QApplicationPrivate4initEv+0x9)[0x7ff2b1b48ab9]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17ecf0)[0x7ff2b226ccf0]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17ed62)[0x7ff2b226cd62]
/home/mitchell/anaconda3/envs/DEEPLABCUT/lib/python3.8/site-packages/PySide6/QtWidgets.abi3.so(+0x17f3e2)[0x7ff2b226d3e2]
python(_PyObject_MakeTpCall+0x51c)[0x56135495155c]
python(_PyEval_EvalFrameDefault+0x4d64)[0x56135494d374]
python(_PyFunction_Vectorcall+0xf6)[0x5613549591d6]
python(_PyEval_EvalFrameDefault+0x38b)[0x56135494899b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x561354947351]
python(PyEval_EvalCodeEx+0x39)[0x561354a06fe9]
python(PyEval_EvalCode+0x1b)[0x561354a06fab]
python(+0x1df30d)[0x561354a0b30d]
python(+0x12deb8)[0x561354959eb8]
python(_PyEval_EvalFrameDefault+0x38b)[0x56135494899b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x561354947351]
python(_PyFunction_Vectorcall+0x18c)[0x56135495926c]
python(_PyEval_EvalFrameDefault+0x38b)[0x56135494899b]
python(_PyEval_EvalCodeWithName+0x2e1)[0x561354947351]
python(_PyFunction_Vectorcall+0x18c)[0x56135495926c]
python(PyObject_Call+0x2d2)[0x56135496b0a2]
python(+0x1f805b)[0x561354a2405b]
python(Py_RunMain+0xcc)[0x561354a2389c]
python(Py_BytesMain+0x39)[0x5613549fb329]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7ff3d673ad90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7ff3d673ae40]
python(+0x1cf235)[0x5613549fb235]
*** END MANGLED STACK TRACE ***

*** Begin stack trace ***
	tsl::CurrentStackTrace[abi:cxx11]()
	
	
	pthread_kill
	raise
	abort
	
	QMessageLogger::warning(char const*, ...) const
	
	QGuiApplicationPrivate::createPlatformIntegration()
	QGuiApplicationPrivate::createEventDispatcher()
	QCoreApplicationPrivate::init()
	QGuiApplicationPrivate::init()
	QApplicationPrivate::init()
	
	
	
	_PyObject_MakeTpCall
	_PyEval_EvalFrameDefault
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	PyEval_EvalCodeEx
	PyEval_EvalCode
	
	
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	_PyEval_EvalFrameDefault
	_PyEval_EvalCodeWithName
	_PyFunction_Vectorcall
	PyObject_Call
	
	Py_RunMain
	Py_BytesMain
	
	__libc_start_main
	
*** End stack trace ***
Aborted (core dumped)
```
