### ISSUE TITLE
FileNotFoundError for analyze_videos in example notebook

### ISSUE THREAD

**Issue by tbenst** [DeepLabCut/DeepLabCut#273]
**Your Operating system and DeepLabCut version**
NixOS, DeepLabCut 2.0.5

**Describe the problem**
When running Colab_DEMO_mouse_openfield, I get the following error on `deeplabcut.analyze_videos(path_config_file,videofile_path)`

```
Config:
{'all_joints': [[0], [1], [2], [3]],
 'all_joints_names': ['snout', 'leftear', 'rightear', 'tailbase'],
 'batch_size': 4,
 'bottomheight': 400,
 'crop': True,
 'crop_pad': 0,
 'cropratio': 0.4,
 'dataset': 'training-datasets/iteration-0/UnaugmentedDataSet_openfieldOct30/openfield_Pranav95shuffle1.mat',
 'dataset_type': 'default',
 'display_iters': 1000,
 'fg_fraction': 0.25,
 'global_scale': 0.8,
 'init_weights': '/nix/store/s21821ky72w5x3w3fhdrgvhqzrvpvs7h-python3-3.7.3-env/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt',
 'intermediate_supervision': False,
 'intermediate_supervision_layer': 12,
 'leftwidth': 400,
 'location_refinement': True,
 'locref_huber_loss': True,
 'locref_loss_weight': 0.05,
 'locref_stdev': 7.2801,
 'log_dir': 'log',
 'max_input_size': 1500,
 'mean_pixel': [123.68, 116.779, 103.939],
 'metadataset': 'training-datasets/iteration-0/UnaugmentedDataSet_openfieldOct30/Documentation_data-openfield_95shuffle1.pickle',
 'minsize': 100,
 'mirror': False,
 'multi_step': [[0.005, 10000],
                [0.02, 430000],
                [0.002, 730000],
                [0.001, 1030000]],
 'net_type': 'resnet_50',
 'num_joints': 4,
 'optimizer': 'sgd',
 'pos_dist_thresh': 17,
 'project_path': '/home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30',
 'regularize': False,
 'rightwidth': 400,
 'save_iters': 50000,
 'scale_jitter_lo': 0.5,
 'scale_jitter_up': 1.25,
 'scoremap_dir': 'test',
 'shuffle': True,
 'snapshot_prefix': '/home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/dlc-models/iteration-0/openfieldOct30-trainset95shuffle1/test/snapshot',
 'stride': 8.0,
 'topheight': 400,
 'use_gt_segm': False,
 'video': False,
 'video_batch': False,
 'weigh_negatives': False,
 'weigh_only_present_joints': False,
 'weigh_part_predictions': False,
 'weight_decay': 0.0001}

Using snapshot-3100 for model /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/dlc-models/iteration-0/openfieldOct30-trainset95shuffle1
INFO:tensorflow:Restoring parameters from /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/dlc-models/iteration-0/openfieldOct30-trainset95shuffle1/train/snapshot-3100

Restoring parameters from /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/dlc-models/iteration-0/openfieldOct30-trainset95shuffle1/train/snapshot-3100

Starting to analyze %  /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4
Loading  /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/nix/store/s21821ky72w5x3w3fhdrgvhqzrvpvs7h-python3-3.7.3-env/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in AnalyzeVideo(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder)
    262         # Attempt to load data...
--> 263         pd.read_hdf(dataname)
    264         print("Video already analyzed!", dataname)

/nix/store/s21821ky72w5x3w3fhdrgvhqzrvpvs7h-python3-3.7.3-env/lib/python3.7/site-packages/pandas/io/pytables.py in read_hdf(path_or_buf, key, mode, **kwargs)
    365             raise compat.FileNotFoundError(
--> 366                 'File {path} does not exist'.format(path=path_or_buf))
    367 

FileNotFoundError: File /home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/m3v1mp4DeepCut_resnet50_openfieldOct30shuffle1_3100.h5 does not exist

During handling of the above exception, another exception occurred:

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-23-6e0cc4b654ab> in <module>
      1 videofile_path = [ex_dir + 'openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4'] #Enter the list of videos to analyze.
----> 2 deeplabcut.analyze_videos(path_config_file,videofile_path)

/nix/store/s21821ky72w5x3w3fhdrgvhqzrvpvs7h-python3-3.7.3-env/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in analyze_videos(config, videos, videotype, shuffle, trainingsetindex, gputouse, save_as_csv, destfolder)
    151         #looping over videos
    152         for video in Videos:
--> 153             AnalyzeVideo(video,DLCscorer,trainFraction,cfg,dlc_cfg,sess,inputs, outputs,pdindex,save_as_csv, destfolder)
    154 
    155     os.chdir(str(start_path))

/nix/store/s21821ky72w5x3w3fhdrgvhqzrvpvs7h-python3-3.7.3-env/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/predict_videos.py in AnalyzeVideo(video, DLCscorer, trainFraction, cfg, dlc_cfg, sess, inputs, outputs, pdindex, save_as_csv, destfolder)
    269         fps = cap.get(5) #https://docs.opencv.org/2.4/modules/highgui/doc/reading_and_writing_images_and_video.html#videocapture-get
    270         nframes = int(cap.get(7))
--> 271         duration=nframes*1./fps
    272         size=(int(cap.get(4)),int(cap.get(3)))
    273 

ZeroDivisionError: float division by zero
```

I think the path we want is `/home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/evaluation-results/iteration-0/openfieldOct30-trainset95shuffle1/DeepCut_resnet50_openfieldOct30shuffle1_3500-snapshot-3500.h5`, but per the error `/home/tyler/lib/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/m3v1mp4DeepCut_resnet50_openfieldOct30shuffle1_3100.h5` does not exist. I stopped training at 3950 epochs.

**Comment by MMathisLab** [comment]
Seems the video is not found (as it can't read the fps). The default values are:

```
videofile_path = ['/content/drive/My Drive/DeepLabCut/examples/openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4'] #Enter the list of videos to analyze.
deeplabcut.analyze_videos(path_config_file,videofile_path)
```
are you running this step on Colab? I would check the video is where you point to with v`ideofile_path`

**Comment by MMathisLab** [comment]
Hi @tbenst is this resolved now? (With the correct path I cannot reproduce your error)

**Comment by tbenst** [comment]
Hi @MMathisLab, sorry for my delay. The issue is not resolved, and the path is there:
```python
videofile_path = [ex_dir + 'openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4'] #Enter the list of videos to analyze.
assert os.path.isfile(videofile_path[0])
deeplabcut.analyze_videos(path_config_file,videofile_path)
```
And then the same error occurs as above.

I'm running this locally. The error is about an h5 file that is not there. Could you reopen?

**Comment by MMathisLab** [comment]
you you post the full call, with variables, and the error. i.e. IDk what ex_dir is. Also, you stopped at 39XX, is the 3100 saved in the dlc-models folder?

**Comment by tbenst** [comment]
I can reproduce the same error on Demo_labeledexample_MouseReaching. I train to 610 iterations, and `saveiters=300`.

Here's the notebook with output: https://gist.github.com/tbenst/c2b070f0c38ff5f262a3b542dcc93a11

Thanks for your help!

**Comment by MMathisLab** [comment]
`deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='.mp4')`

avi is the default, so likely that is why it cannot read the video from the openfield data

**Comment by tbenst** [comment]
Sorry I don't understand..I am using the default .avi. I haven't changed anything in the notebook other than giving the path.

**Comment by MMathisLab** [comment]
```
videofile_path = [ex_dir + 'openfield-Pranav-2018-10-30/videos/m3v1mp4.mp4'] #Enter the list of videos to analyze.
assert os.path.isfile(videofile_path[0])
deeplabcut.analyze_videos(path_config_file,videofile_path)
```
since the video is an mp4, the last line should be: `deeplabcut.analyze_videos(path_config_file,videofile_path, videotype='.mp4')`

**Comment by tbenst** [comment]
fixed the issue! The problem was that deeplabcut need opencv to be compiled with ffmpeg.

**Comment by MMathisLab** [comment]
awe yes, a classic ie #54 - in case others find this error too...  glad it works now for you.
