### ISSUE TITLE
Extract_outlier_frames GUI not responsive

### ISSUE THREAD

**Issue by WernTanj** [DeepLabCut/DeepLabCut#654]
CentOS, 7
DLC 2.1.6.2.

deeplabcut.extract_outlier_frames (config_path, [‘path to original videos for training’], outlieralgorithm = ‘manual’ )

1) Move slide-bar to frame of interest
1) Grab frame
2) Move slide-bar to new location
3) All labels and the frame are not in sync i.e. the labels mirroring a mouse spine are not where the mouse is - maybe the frame and label index are off-set?
4) Move slide-bar again
5) GUI freezes and is unresponsive
6) close GUI

trace back:
```
>>> deeplabcut.extract_outlier_frames(config_path,['/data/DLC/movies/200312_ext_site/site_II/site_12.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_15.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_16.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_18.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_19.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_1.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_2.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_5.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_6.avi',
... '/data/DLC/movies/200312_ext_site/site_II/site_9.avi'],outlieralgorithm ='manual')
/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py:322: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  DF = self.Dataframe.ix[[self.currFrame]]
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12454 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12454 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 359, in grabFrame
    self.chooseFrame()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 322, in chooseFrame
    DF = self.Dataframe.ix[[self.currFrame]]
  File "/data/venvs/DLC/lib/python3.6/site-packages/pandas/core/indexing.py", line 148, in __getitem__
    return self._getitem_axis(key, axis=axis)
  File "/data/venvs/DLC/lib/python3.6/site-packages/pandas/core/indexing.py", line 1022, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/data/venvs/DLC/lib/python3.6/site-packages/pandas/core/indexing.py", line 1133, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "/data/venvs/DLC/lib/python3.6/site-packages/pandas/core/indexing.py", line 1092, in _get_listlike_indexer
    keyarr, indexer, o._get_axis_number(axis), raise_missing=raise_missing
  File "/data/venvs/DLC/lib/python3.6/site-packages/pandas/core/indexing.py", line 1177, in _validate_read_indexer
    key=key, axis=self.obj._get_axis_name(axis)
KeyError: "None of [Int64Index([12454], dtype='int64')] are in the [index]"
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 246, in updateSlider
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12460 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 246, in updateSlider
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12700 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 17094 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 17094 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 19780 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 19780 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12454 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 12454 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 15018 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 15018 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 18559 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 18559 is out of bounds for axis 0 with size 10501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 283, in OnSliderScroll
    self.update()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 296, in update
    frame=img_as_ubyte(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
cv2.error: OpenCV(4.2.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 279, in OnSliderScroll
    self.figure.delaxes(self.figure.axes[1])
IndexError: list index out of range
```

In general, the GUI for extract_outlier_frames works less smooth than the extract_frames GUI e.g. the slide-bar does not respond very well (with different bar-widths) the GUI freezes from time to time. Are the two GUIs coded very differently?

I can provide the videos and files if it helps to reproduce the issue.

**Comment by MMathisLab** [comment]
the ix, iloc was already fixed; please update dlc to the latest version. 2.16.4

**Comment by MMathisLab** [comment]
@WernTanj - if using Manual you can only pass one file at a time.. if not, then yeah it's a mess!

**Comment by WernTanj** [comment]
Hi!

I upgraded to the latest dlc version and passed only one video file. But it seems that the indexing issue persists.

CentOS 7, DLC 2.1.6.5
extract_outlier_frames(config_path, 'one .avi file', outlieralgorithm: ‘manual’)

1) load movie - 170fps / 1440 x 1080
1) use sidebar to scroll through video
2) example screenshot below: labels do not match the frame
3) no traceback in the terminal


deeplabcut.extract_outlier_frames(config_path,['/data/DLC/movies/200312_ext_floor/floor_13.avi'],outlieralgorithm ='manual')

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 1570 is out of bounds for axis 0 with size 1501

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 1570 is out of bounds for axis 0 with size 1501

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 1780 is out of bounds for axis 0 with size 1501

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 1780 is out of bounds for axis 0 with size 1501

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 2076 is out of bounds for axis 0 with size 1501

Traceback (most recent call last):

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll

   self.plot_labels()

 File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels

   self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]

IndexError: index 2076 is out of bounds for axis 0 with size 1501

**Comment by WernTanj** [comment]
Hi,

It seems that the problem with indexing persists in the latest dlc upgrade.

CentOS 7, DLC 2.1.7
extract_outlier_frames(config_path, 'one .avi file', outlieralgorithm= ‘manual’)

1) load movie - 170fps / 1440 x 1080
2) use sidebar to scroll through video
 - first 3 frames show correct label location in the frame - continue scrolling
 - then the labels do not match the frame anymore - continue scrolling
 - no more labels visible in the frame 
3) traceback in the terminal
>>> deeplabcut.extract_outlier_frames(config_path,['/data/DLC/movies/video.avi'], outlieralgorithm='manual')
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 1780 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 1780 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2041 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2041 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2373 is out of bounds for axis 0 with size 1501
Traceback (most recent call last):
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 284, in OnSliderScroll
    self.plot_labels()
  File "/data/venvs/DLC/lib/python3.6/site-packages/deeplabcut/refine_training_dataset/outlier_frame_extraction_toolbox.py", line 380, in plot_labels
    self.points = [self.Dataframe[self.scorer][bp]['x'].values[self.currFrame],self.Dataframe[self.scorer][bp]['y'].values[self.currFrame],1.0]
IndexError: index 2373 is out of bounds for axis 0 with size 1501

**Comment by MMathisLab** [comment]
Your video is massive, and this is not going to be possible in such a scenario, i.e frames > 1k x 1K pixels at 170 FPS; to extract outliers we recommend using (1) the automatic methods, (2) only using short clips of video where you know a super rare event occurs that you missed with our clustering tools. There are very very few programs that can handle such video editing; people are working on them (such as napari) but as you see, many video programs like BORIS, etc aren't going to handle such massive files... 


Here is the GUI on the DEMO video data - which is about the max I would recomment, and I have no issues:

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/28102185/80891338-57d5d700-8c91-11ea-9be4-ba786bcdba6c.gif)

**Comment by WernTanj** [comment]
I am aware that such movies challenge current video analysis tools. Thus, I am already working with short video clips (1 min) containing diverse behaviors for labeling and training. With 170fps the automatic frame extraction results in lots of similar frames. So I had to do it either iteratively- exract/delete similar frames/ extract etc. or just manual. Temporal downsampling is not an option since tracking paws in an open field scenario is tricky and does not work properly with 30fps. I can try spatial downsampling to ease the process.
