### ISSUE TITLE
Version 2.2b5 unable to analyze videos after training (get_nframes_robust()/ffprobe)

### ISSUE THREAD

**Issue by kretsge** [DeepLabCut/DeepLabCut#713]
OS: Windows 10
DeepLabCut Version: 2.2b5
Anaconda env used: DLC-GPU

Hi! I've just started to transition to version 2.2 for multi-animal tracking. I've been working almost entirely within the Project Manager (though I previously used older versions of DLC in a jupyter notebook).

I set up my first multi-animal project and it seemed to be going smoothly through the evaluate network stage. After evaluate it successfully made the example maps. When I went to analyze the videos, however, I started getting an error and I don't know what to make of it. Thanks for any help you can provide!

I'm not sure if it's relevant or a separate issue, but I also had some issues with the skeleton (it said "no fully labelled animal was found") but thought it might still work since the training/evaluation seemed ok. If you think I need to go back and resolve that first, let me know!
```
The terminal looked like this:
(dlc-windowsGPU) D:\>python -m deeplabcut
Starting GUI...
note to user: currently only ResNet50-v1 is available for maDLC
note to user: currently model comparision is not available in maDLC
Analyzing ...
Using snapshot-200000 for model D:\Users\rhush\Desktop\Direct2VIPscope_MultiAnimalDLC-LK-2020-05-25\dlc-models\iteration-0\Direct2VIPscope_MultiAnimalDLCMay25-trainset95shuffle1
Initializing ResNet
Activating extracting of PAFs
2020-05-29 12:16:52.185776: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2020-05-29 12:16:52.882906: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1433] Found device 0 with properties:
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
totalMemory: 8.00GiB freeMemory: 6.64GiB
2020-05-29 12:16:52.904238: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1512] Adding visible gpu devices: 0
2020-05-29 12:16:53.819234: I tensorflow/core/common_runtime/gpu/gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-05-29 12:16:53.830185: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990]      0
2020-05-29 12:16:53.836555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1003] 0:   N
2020-05-29 12:16:53.844706: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6387 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1070, pci bus id: 0000:02:00.0, compute capability: 6.1)
Starting to analyze %  D:\Users\rhush\Desktop\Direct2VIPscope_MultiAnimalDLC-LK-2020-05-25\test_iteration0\behavCam2_414d2t1.avi
D:\Users\rhush\Desktop\Direct2VIPscope_MultiAnimalDLC-LK-2020-05-25\test_iteration0  already exists!
Loading  D:\Users\rhush\Desktop\Direct2VIPscope_MultiAnimalDLC-LK-2020-05-25\test_iteration0\behavCam2_414d2t1.avi
Traceback (most recent call last):
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\gui\analyze_videos.py", line 477, in analyze_videos
    robust_nframes=robust,
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_videos.py", line 300, in analyze_videos
    robust_nframes=robust_nframes,
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\pose_estimation_tensorflow\predict_multianimal.py", line 57, in AnalyzeMultiAnimalVideo
    nframes = auxfun_videos.get_nframes_robust(video)
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\site-packages\deeplabcut\utils\auxfun_videos.py", line 293, in get_nframes_robust
    output = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\rhush\Anaconda3\envs\dlc-windowsGPU\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'ffprobe -i D:\Users\rhush\Desktop\Direct2VIPscope_MultiAnimalDLC-LK-2020-05-25\test_iteration0\behavCam2_414d2t1.avi -v error -count_frames -select_streams v:0 -show_entries stream=nb_read_frames -of default=nokey=1:noprint_wrappers=1' returned non-zero exit status 1.
```
Thank you!

**Comment by AlexEMG** [comment]
Related to https://github.com/DeepLabCut/DeepLabCut/issues/711 (and fixed with that commit)

This version is only required if you have: robust_nframes=True

**Comment by MMathisLab** [comment]
@kretsge - but I guess you did indeed connect the skeleton before you trained? i.e, every body part must be connected. The GUI is just to help you do this, but if you are labeling data where there is not even a single frame with all points, then you need to do this manually:

https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/functionDetails.md#b-configure-the-project-

**Comment by PolarBean** [comment]
I'm still getting the same issue on 2.2.b5 
![issue](https://user-images.githubusercontent.com/38996929/83348644-e5304800-a371-11ea-899a-fb347bc864b1.PNG)

**Comment by Kat-8-S** [comment]
Hi,

I've read comment #711, but am also running into this same error message this morning running this function on google colab with a Windows 10 computer. 

Could you please clarify what we should modify in the script to resolve this error? I tried adding robust_nframes=True to the deeplabcut.analyze_videos call, but still get this error message.

Thank you!

**Comment by MMathisLab** [comment]
Right now you’d have to install from the source code, not pypi. 

Ie replace `pip install deeplabcut` With 

`pip install git+git://github.com/DeepLabCut/DeepLabCut`

**Comment by Kat-8-S** [comment]
I'm sorry for making this thread longer. 

I've made that change in my colab script, but it hasn't fixed the error in analyze_video.

**Comment by MMathisLab** [comment]
No problem. Can you post exactly what you are inputting? I just ran COLAB, and I have no issues analyzing files. I am concerned the path you are inputting is wrong, project_path is incorrect, or the video is corrupted; you can open the video with VLC, etc?

Here is me ~5 min ago, using this notebook: https://github.com/DeepLabCut/DeepLabCut/blob/master/examples/COLAB_maDLC_TrainNetwork_VideoAnalysis.ipynb

Install from git:
![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/28102185/83422918-3aaf3800-a3f8-11ea-8c57-360b2e156f97.gif)

running video analysis:
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/28102185/83422942-43077300-a3f8-11ea-83a3-c8c0fc646266.gif)

**Comment by Kat-8-S** [comment]
Thank you for your help!

It looks like the problem is fixed and the script is now running. The only change I made was to use the script variables as you've done in the video rather than typing them in myself when calling analyze_videos. 

I'll attach the images.

A- non-working call.
![Image](https://user-images.githubusercontent.com/65971162/83426476-2d487c80-a3fd-11ea-8a4e-cd49e0ef5d7d.PNG)

B- fixed call.
![Image 2](https://user-images.githubusercontent.com/65971162/83426482-30dc0380-a3fd-11ea-9ebb-943c82e0a0d6.PNG)
