### ISSUE TITLE
Cross validation of multiple iterations give results of only one in results.csv

### ISSUE THREAD

**Issue by AntoineCribel** [DeepLabCut/DeepLabCut#947]
After evaluating my network (with multiple iterations and snapshot_index = all), I tried to cross validate all iterations with evaluate_multianimal_crossvalidate. Then this should fill the results.csv file in the evaluation-results folder with all rmse (amongs other metrics) of all iterations. However in my case, only the results of one iteration are written in the file. 

I am running DLC 2.2b8 on Linux with a multianimal project.

**Comment by MMathisLab** [comment]
sorry, where in the docs does it say that x-validation is for all snapshots? 

To me, it only says this for evalute_network....

**Comment by AntoineCribel** [comment]
Oh sorry, I guessed it was supposed to be the case since @jeylau answered me that it should work like that here: https://forum.image.sc/t/test-error-worse-after-extracting-outlier-frames-refining-labels/42662/6

But then I think it would be quite useful if that would be possible.

**Comment by MMathisLab** [comment]
He answered that the file (i.e., 1), would be in the evaluation_results folder; the "all"  was referring to network evaluation for pose estimation. The way it works is perhaps not clear; first, you need to do pose estimation and pick the best network (hence the evaluate all); then you go forward with this best network, and optimize tracking, which is what x-validation does. 

See more here: https://github.com/DeepLabCut/DeepLabCut/blob/master/docs/maDLC_AdvUserGuide.md#attention 

So, I'm not sure how that would be useful, i.e. it's unrelated to pose estimation performance, in the sense you should only be using the best one at this point, and x-validating on "all" would constantly update the inference_cfg.yaml

**Comment by AntoineCribel** [comment]
Thanks! Okay now I understand why it doesn't make sense to compare iterations after the cross-validation. However it's still unclear to me how I can decide which training iteration is the best to keep. Wouldn't it make sense to be able to check how the rmse vary with the number of training iteration with multianimal networks (like in the link above)? Also that way we could compare how the test and train rmse vary with the number of iterations and thus have an idea about when we start to overtrain the network

**Comment by MMathisLab** [comment]
^ yes, of course, but that is `evaluate_network` this does this for both single animal and multi-animal projects; you can evaluate all snapshots that you kept, default is only 5 as each is ~100 MB. If you keep many more, you can make the RMSE vs. Iteration # plot and decide / also looking at the output images is very useful to check as well.

**Comment by AntoineCribel** [comment]
Yes that was my initial idea and what my first question (on forum.image.sc) was about. I don't know were I can find the .csv file with those rmse for all iteration after evaluating the network. From @jeylau answer, I though it should be in the results.csv.

**Comment by MMathisLab** [comment]
<img width="665" alt="Screen Shot 2020-10-07 at 6 11 23 PM" src="https://user-images.githubusercontent.com/28102185/95357715-843cf180-08c8-11eb-875f-1173627c9df9.png">

For pose estimation, indeed the results are stored (see image) as here! Hope that helps!

**Comment by AntoineCribel** [comment]
Oups I thought I answered. Yes that helps but sadly it seems like there is something wrong in my case. I don't see those '-results.csv' or '-snapshot.h5' files after running `evaluate_network`. Only the labeledImages folders (when plotting=True) and _full.pickles files are generated for each iterations. So I only have one results.csv file and one .h5 file (from the best iteration I think).

I also have "RuntimeWarning: All-NaN slice encountered" messages for each iterations, but I don't think it's related because the 
Euclidian distance statistics are displayed during the evaluation.

**Comment by AntoineCribel** [comment]
Is it possible to re-open this issue? Since the '-results.csv' files are not generated as they should

**Comment by MMathisLab** [comment]
the issue was you wanted to evaluate all for x-validation, which doesn't, to me, make sense given what we discussed above; so in that sense, the issue is resolved. 

But, you are saying you don't get evaluation metrics in the terminal or under eval results, which look like this for maDLC (indeed what I posted above was for single animal DLC): i.e., you get the following h5 and pickle files that are needed for downstream steps.

![Screen Shot 2020-10-22 at 6 00 29 PM](https://user-images.githubusercontent.com/28102185/96898934-943ffe00-1490-11eb-9e37-114396e550a0.png)

**Comment by AntoineCribel** [comment]
Sorry and indeed, this issue was "solved". However I still don't know how I can get the rmse for the various iterations in a maDLC project. These evaluation metrics are shown in the terminal when I evaluate the different iterations. But they are not written in the single results.csv (only for one iteration). Similarly there is only one .h5 file that is created after evaluation.

So is there a way with a maDLC project to get those evaluation metrics for each saved iterations? If not I think it would be quite useful (like for a simple DLC project) to have them in separate .csv files

**Comment by GPU-Shuttle** [comment]
The .csv file in my evaluation-results folder only contains one row that shows the values for the very last iteration! 
Any suggestions on how it would be possible to have the values for all the other iterations as well, please?

**Comment by jeylau** [comment]
Set `snapshotindex` to `'all'` in the config.yaml file. ☺️  Note that it is `-1` by default, thus only evaluating the last snapshot.

**Comment by GPU-Shuttle** [comment]
Fantastic! Thanks for that @jeylau
